# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Logistic gradient
#'
#' @param data A matrix with the data to use
#' @param theta The coefficient vector
#' @param idx The rows to use (base 0 for now)
#' @export
logisticG <- function(theta, data, idx) {
    .Call(`_irls_sgd_logisticG`, theta, data, idx)
}

#' Gaussian gradient
#'
#' @param data A matrix with the data to use
#' @param theta The coefficient vector
#' @param idx The rows to use (base 0 for now)
#' @export
gaussianG <- function(theta, data, idx) {
    .Call(`_irls_sgd_gaussianG`, theta, data, idx)
}

